; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = genericSTM32F405RG

[env:genericSTM32F405RG]
platform = ststm32
board = genericSTM32F405RG
framework = arduino
monitor_speed = 115200
lib_archive = false
lib_deps =
    askuric/Simple FOC@^2.4.0
build_flags =
    -D PIO_FRAMEWORK_ARDUINO_ENABLE_CDC
    -D MOTOR_POLE_PAIRS=7
    -D SUPPLY_VOLTAGE=12.0f
    -D VOLTAGE_LIMIT=2.0f
    -D VELOCITY_LIMIT=20.0f
