
;Project BLDC FOC Drive

[env:genericSTM32F405RG]
platform = ststm32
board = genericSTM32F405RG
framework = arduino
monitor_speed = 115200
upload_protocol = stlink

lib_deps = 
	stm32duino/STM32duino FreeRTOS @ ^10.3.1

